### ISSUE TITLE
CKTON Staking is not producing CRAB Rewards

### ISSUE THREAD

**Issue by 2xJDubs** [darwinia-network/KtonDAO#24]
CKTON Staking is currently not producing any Crab Rewards. I claimed the CRAB rewards I had about 14 hours ago and since then have not seen any rewards accumulate.  This was also reported by another community member.  Here is the claim transaction and a screen shot of my CKTON staking dashboard.

https://crab-scan.darwinia.network/tx/0x1787cb57c20a079aab28f5333a57737588aae3abf0f182429d3f366daaac097b

![image](https://github.com/user-attachments/assets/70fd2a4c-6b0d-419d-a300-f70ded42b704)

When looking at the Governance contract I am not seeing any seeding of CRAB to the contract and I wonder if that is why no rewards are being accumulated.

https://crab-scan.darwinia.network/address/0xB633Ad1142941CA2Eb9C350579cF88BbE266660D?tab=token_transfers

**Comment by hackfisher** [comment]
Thanks for reporting, known issue need upgrade runtime to fix it.

https://github.com/darwinia-network/darwinia/issues/1604

Only affect Crab, do not affect Darwinia.

**Comment by hackfisher** [comment]
Fixed.
